### ISSUE TITLE
npm word library

### ISSUE THREAD

**Issue by Ehawk82** [Ehawk82/hangman#13]
we need to be able to call random word from the module with a user invoke

**Comment by Ehawk82** [comment]
browserfy allows us to bundle modules and call them at DOM onload.  We need to me able to invoke the module dynamically.

**Comment by StoneCypher** [comment]
k so

you need basically four things here

1. random numbers
1. a way to get them out of a module
1. a way to pick a word from a container
1. some user invokation

so like

----

# random numbers

`Math.random()` will give you a random number at or above 0 and below 1. 

So let's say you want a six sided die.  That means you should get any of the six values `[1,2,3,4,5,6]`.

`Math.random()` gives you 0.. <1 (that is, it can give you 0.999999, but it can't give you exactly 1.)

Okay.  So let's multiply it by 6.  Now we have 0.. <6.  Also, all the values in 5-6 are equally likely as all the values in 0-1.

Next, let's use `Math.floor()` to chop off the fraction part.  Now it's 0-5 (because it wasn't allowed to quite hit 6, remember.)

Finally, let's add one.  Pow!  1-6.

To check if it's good, write a function that rolls it ten million times and increments an array element at the given location.  Check, at the end, that the locations are around the same count (since it's random, they won't be exactly matching, but when you're in big counts like ten million, the `law of large numbers` should take over like it does for casinos, and you should get a very close-to-expected result.)

"What's the `law of large numbers`?"

Assuming a perfect set of dice, the more times you roll them, the closer the group will get to the statistical expected outcomes.

That is, if you only roll a die six times, the likelihood that you'll get one of each is pretty low.  But if you roll it six billion times, the likelihood that you'll get about one billion of each (assuming the die doesn't fail) is very, very high.

As the roll count goes up, the "normality" of the distribution increases.  Surprisingly rapidly, actually; these tests are usually okay in the tens of thousands (but since it's just math.rand, which is stupid fast, why not do ten million?  It's not like you'll notice the wait.)

----

# Getting them out of a module

Let's talk on messenger.  You should be in [rollup](https://rollupjs.org/guide/en/), which is made for modern code, not browserify, which is made for what is these days legacy code.

However, getting started in rollup isn't straightforward.  I'll help.

At the end, you will just

```javascript
const words = ['thing', 'other thing', 'butt'];
export { words };
```

and elsewhere,

```javascript
import { words } from './some_file.js';
```

----

Picking from a container

honestly this is easy once you have the randomness function and your bundler worked out.  

----

then i don't know what your goals are around UI
